import { Card } from "./card";

export const cards: Card[] = [
    {
        id:-1,
        value:"clownfish.png",
        visibility:""
    },
    {
        id:-1,
        value:"clownfish.png",
        visibility:""
    },
    {
        id:-1,
        value:"jellyfish.png",
        visibility:""
    },
    {
        id:-1,
        value:"jellyfish.png",
        visibility:""
    },
    {
        id:-1,
        value:"octopus.png",
        visibility:""
    },
    {
        id:-1,
        value:"octopus.png",
        visibility:""
    },
    {
        id:-1,
        value:"sea-snail.png",
        visibility:""
    },
    {
        id:-1,
        value:"sea-snail.png",
        visibility:""
    },
    {
        id:-1,
        value:"sea-turtle.png",
        visibility:""
    },
    {
        id:-1,
        value:"sea-turtle.png",
        visibility:""
    },
    {
        id:-1,
        value:"shark.png",
        visibility:""
    },
    {
        id:-1,
        value:"shark.png",
        visibility:""
    },
    {
        id:-1,
        value:"shrimp.png",
        visibility:""
    },
    {
        id:-1,
        value:"shrimp.png",
        visibility:""
    },
      {
        id:-1,
        value:"starfish.png",
        visibility:""
    },
    {
        id:-1,
        value:"starfish.png",
        visibility:""
    }]

  