import { Card } from "./card";

export const cards: Card[] = [
    {
        id:0,
        value:"clownfish.png",
        visibility:""
    },
    {
        id:1,
        value:"clownfish.png",
        visibility:""
    },
    {
        id:2,
        value:"jellyfish.png",
        visibility:""
    },
    {
        id:3,
        value:"jellyfish.png",
        visibility:""
    },
    {
        id:4,
        value:"octopus.png",
        visibility:""
    },
    {
        id:5,
        value:"octopus.png",
        visibility:""
    },
    {
        id:6,
        value:"sea-snail.png",
        visibility:""
    },
    {
        id:7,
        value:"sea-snail.png",
        visibility:""
    },
    {
        id:8,
        value:"sea-turtle.png",
        visibility:""
    },
    {
        id:9,
        value:"sea-turtle.png",
        visibility:""
    },
    {
        id:10,
        value:"shark.png",
        visibility:""
    },
    {
        id:11,
        value:"shark.png",
        visibility:""
    },
    {
        id:12,
        value:"shrimp.png",
        visibility:""
    },
    {
        id:13,
        value:"shrimp.png",
        visibility:""
    },
      {
        id:14,
        value:"starfish.png",
        visibility:""
    },
    {
        id:15,
        value:"starfish.png",
        visibility:""
    }]

  